// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title GasSpend
 * @notice A gas-fee ledger + rebate vault for the Ronin network.
 *
 * Why this contract exists
 * ------------------------
 * Ronin's "Proof of Distribution" (PoD) rewards builders for the on-chain
 * activity generated by the contracts they register. One of the six scored
 * dimensions is **Gas Spend** — the RON fees users pay to the Ronin
 * treasury by transacting with your registered contracts.
 *
 * GasSpend makes gas spend the *product*:
 *   1. Users interact with this contract (register, logActivity, claim).
 *      Every interaction is a real transaction that pays gas in RON.
 *   2. The contract measures and permanently records the gas each user
 *      spent (via gasleft() deltas + a fixed per-tx base).
 *   3. The owner funds a RON rebate pool; users earn a rebate proportional
 *      to the gas they spent, so they are incentivised to keep using it —
 *      which keeps generating the gas-fee volume PoD scores.
 *
 * Recovery mechanism
 * ------------------
 * The owner can recover UNCLAIMED rebates at ANY time:
 *   - recoverUnclaimed(user)   -> claw back one user's unclaimed rebate
 *   - recoverAllUnclaimed()    -> claw back every user's unclaimed rebate
 * This is an owner-controlled design (users are expected to claim
 * regularly). Already-claimed RON can never be taken back, and the
 * emergencyWithdraw() surplus rule is unchanged.
 *
 * Security notes: checks-effects-interactions, reentrancy guard on all
 * value-moving functions, rebate obligations tracked so the owner's
 * emergencyWithdraw can never touch user balances except via recovery.
 *
 * @author Built for Ronin PoD Season 3
 */
contract GasSpend {
    // ------------------------------------------------------------------ //
    // Constants & state                                                    //
    // ------------------------------------------------------------------ //
    /// @dev Fixed per-tx overhead (tx base cost ~21,000 gas) added to the
    ///      measured gasleft() delta, so recorded gas is close to real usage.
    uint256 public constant BASE_GAS = 21_000;

    address public owner;
    address public treasury;
    bool public paused;

    /// @dev RON (wei) rebated per unit of gas recorded (e.g. 1 gwei per 1M gas).
    uint256 public rebatePerGas;

    /// @dev Total RON (wei) currently owed to users (cannot be drained by
    ///      emergencyWithdraw; only recoverUnclaimed / recoverAllUnclaimed
    ///      move it, and only back to the owner).
    uint256 public totalOwed;
    uint256 public totalRebatesClaimed;
    uint256 public totalRecovered;

    /// @dev Lifetime gas ledger (gas units).
    uint256 public totalGasSpent;
    uint256 public totalCalls;
    uint256 public totalUsers;

    /// @dev Grow-only list of user addresses (enables recoverAllUnclaimed
    ///      and cheap on-chain leaderboards).
    address[] public userList;
    mapping(address => uint256) private userIndex; // 1-based: 0 = not listed

    struct User {
        bool registered;
        uint256 gasSpent;   // cumulative gas units this user generated
        uint256 claimable;  // RON (wei) owed to this user
        uint256 lastClaim;  // block.timestamp of last claim
    }
    mapping(address => User) public users;

    // ------------------------------------------------------------------ //
    // Events                                                               //
    // ------------------------------------------------------------------ //
    event Registered(address indexed user, uint256 timestamp);
    event Activity(address indexed user, uint256 gasUsed, uint256 cumulativeGas, uint256 timestamp, bytes32 context);
    event RebateClaimed(address indexed user, uint256 amount, uint256 timestamp);
    event RebatesRecovered(address indexed user, uint256 amount, uint256 timestamp);
    event RebatePerGasSet(uint256 value, address setter);
    event TreasurySet(address treasury, address setter);
    event PauseToggled(bool state);
    event EmergencyWithdraw(address to, uint256 amount);

    error Unauthorized();
    error Paused();
    error NotRegistered();
    error AlreadyRegistered();
    error NothingToClaim();
    error ZeroAddress();
    error InvalidPool(uint256 owed, uint256 balance);

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }
    modifier whenNotPaused() {
        if (paused) revert Paused();
        _;
    }
    bool private _locked;
    modifier nonReentrant() {
        require(!_locked, "REENTRANCY");
        _locked = true;
        _;
        _locked = false;
    }

    // ------------------------------------------------------------------ //
    // Constructor                                                          //
    // ------------------------------------------------------------------ //
    constructor(address _treasury, uint256 _rebatePerGas) {
        if (_treasury == address(0)) revert ZeroAddress();
        owner = msg.sender;
        treasury = _treasury;
        rebatePerGas = _rebatePerGas;
        emit TreasurySet(_treasury, msg.sender);
        emit RebatePerGasSet(_rebatePerGas, msg.sender);
    }

    // ------------------------------------------------------------------ //
    // Internal helpers                                                     //
    // ------------------------------------------------------------------ //
    function _addUser(address user) private {
        if (userIndex[user] == 0) {
            userIndex[user] = userList.length + 1;
            userList.push(user);
            totalUsers += 1;
            emit Registered(user, block.timestamp);
        }
    }

    // ------------------------------------------------------------------ //
    // User-facing                                                          //
    // ------------------------------------------------------------------ //

    /// @notice One-time registration. Establishes the user's gas ledger.
    function register() external whenNotPaused {
        User storage u = users[msg.sender];
        if (u.registered) revert AlreadyRegistered();
        u.registered = true;
        _addUser(msg.sender);
    }

    /**
     * @notice The main interaction. Every call is a real transaction that
     *         spends gas; the contract records how much the caller spent.
     * @param context Optional bytes32 tag (session id / product id / referral)
     *        emitted for off-chain analytics. Zero is fine.
     */
    function logActivity(bytes32 context) external whenNotPaused {
        User storage u = users[msg.sender];
        // Auto-register on first interaction (register() then becomes optional).
        if (!u.registered) {
            u.registered = true;
            _addUser(msg.sender);
        }

        uint256 startGas = gasleft();
        // --- measurable work: ledger write + event (kept minimal & honest) ---
        uint256 delta = startGas - gasleft() + BASE_GAS; // gas used *by this call*
        // --- update ledger ---
        u.gasSpent += delta;
        totalGasSpent += delta;
        totalCalls += 1;

        // --- accrue rebate (per unit of gas generated) ---
        if (rebatePerGas > 0) {
            uint256 reward = delta * rebatePerGas;
            u.claimable += reward;
            totalOwed += reward;
        }

        emit Activity(msg.sender, delta, u.gasSpent, block.timestamp, context);
    }

    /// @notice Claim accumulated RON rebates. Reentrancy-safe.
    function claimRebate() external nonReentrant whenNotPaused {
        User storage u = users[msg.sender];
        uint256 amount = u.claimable;
        if (amount == 0) revert NothingToClaim();

        u.claimable = 0;
        u.lastClaim = block.timestamp;
        totalOwed -= amount;

        (bool ok, ) = msg.sender.call{value: amount}("");
        if (!ok) revert("CLAIM_FAILED"); // reverts all state
        totalRebatesClaimed += amount;
        emit RebateClaimed(msg.sender, amount, block.timestamp);
    }

    // ------------------------------------------------------------------ //
    // Owner recovery                                                       //
    // ------------------------------------------------------------------ //

    /// @notice Owner recovers ONE user's unclaimed rebates at any time.
    function recoverUnclaimed(address user) external onlyOwner nonReentrant {
        User storage u = users[user];
        uint256 amount = u.claimable;
        if (amount == 0) revert NothingToClaim();

        u.claimable = 0;
        u.lastClaim = block.timestamp;
        totalOwed -= amount;

        (bool ok, ) = owner.call{value: amount}("");
        if (!ok) revert("RECOVER_FAILED"); // reverts all state
        totalRecovered += amount;
        emit RebatesRecovered(user, amount, block.timestamp);
    }

    /// @notice Owner recovers ALL users' unclaimed rebates in one tx.
    function recoverAllUnclaimed() external onlyOwner nonReentrant {
        uint256 total = 0;
        uint256 n = userList.length;
        for (uint256 i = 0; i < n; i++) {
            address u = userList[i];
            uint256 amt = users[u].claimable;
            if (amt > 0) {
                users[u].claimable = 0;
                users[u].lastClaim = block.timestamp;
                total += amt;
                emit RebatesRecovered(u, amt, block.timestamp);
            }
        }
        if (total == 0) revert NothingToClaim();

        totalOwed -= total;
        (bool ok, ) = owner.call{value: total}("");
        if (!ok) revert("RECOVER_FAILED"); // reverts all state
        totalRecovered += total;
    }

    // ------------------------------------------------------------------ //
    // Owner (admin)                                                        //
    // ------------------------------------------------------------------ //

    /// @notice Accept RON into the rebate pool (or any EOA transfer).
    receive() external payable {}

    /// @notice Set the rebate rate (wei per gas unit). 0 disables rebates.
    function setRebatePerGas(uint256 _rebatePerGas) external onlyOwner {
        rebatePerGas = _rebatePerGas;
        emit RebatePerGasSet(_rebatePerGas, msg.sender);
    }

    /// @notice Change the treasury (info only; PoD portal uses its own registry).
    function setTreasury(address _treasury) external onlyOwner {
        if (_treasury == address(0)) revert ZeroAddress();
        treasury = _treasury;
        emit TreasurySet(_treasury, msg.sender);
    }

    function pause() external onlyOwner { paused = true; emit PauseToggled(true); }
    function unpause() external onlyOwner { paused = false; emit PauseToggled(false); }

    /// @notice Owner can withdraw only the surplus above all user obligations.
    function emergencyWithdraw(address to) external onlyOwner {
        if (to == address(0)) revert ZeroAddress();
        uint256 balance = address(this).balance;
        if (balance <= totalOwed) revert InvalidPool(totalOwed, balance);
        uint256 surplus = balance - totalOwed;
        (bool ok, ) = to.call{value: surplus}("");
        require(ok, "WITHDRAW_FAILED");
        emit EmergencyWithdraw(to, surplus);
    }

    // ------------------------------------------------------------------ //
    // Views                                                                //
    // ------------------------------------------------------------------ //
    function gasSpentOf(address user) external view returns (uint256) { return users[user].gasSpent; }
    function claimableOf(address user) external view returns (uint256) { return users[user].claimable; }
    function isRegistered(address user) external view returns (bool) { return users[user].registered; }
    function poolBalance() external view returns (uint256) { return address(this).balance; }
    function userCount() external view returns (uint256) { return userList.length; }
    function stats() external view returns (uint256 users_, uint256 calls_, uint256 gasSpent_, uint256 owed_) {
        return (totalUsers, totalCalls, totalGasSpent, totalOwed);
    }
// ------------------------------------------------------------------ //
// Heavy interactions (real on-chain work = real gas = real PoD score)  //
// ------------------------------------------------------------------ //
// PoD scores REAL gas fees (gasUsed x gasPrice) from on-chain tx data,
// not anything a contract "records". The only way to raise gas per call
// is to genuinely use more gas: writing permanent storage records is real
// on-chain work and real gas. Each slot write costs ~22.1k gas, so the
// owner caps how many slots one call may write (default 2000 ~= 44M gas,
// safely under Ronin's ~60M block gas limit at 21 gwei ~= 0.93 RON/call).
// Records are real data (session hashes) a frontend can use for analytics.
uint256 public maxHeavySlots = 2_000;

/// @dev Permanent on-chain records written by heavy calls (real data).
mapping(address => bytes32[]) public heavyRecords;

/// @notice High-gas interaction: writes `slots` real session records to
///         permanent storage. Caller pays the real gas for that work.
function logActivityHeavy(bytes32 context, uint256 slots) external whenNotPaused {
    User storage u = users[msg.sender];
    if (!u.registered) {
        u.registered = true;
        _addUser(msg.sender);
    }

    uint256 startGas = gasleft();
    uint256 n = slots > maxHeavySlots ? maxHeavySlots : slots;
    bytes32[] storage recs = heavyRecords[msg.sender];
    for (uint256 i = 0; i < n; i++) {
        // real, unique, permanent on-chain record
        recs.push(keccak256(abi.encodePacked(context, block.number, i)));
    }
    uint256 delta = startGas - gasleft() + BASE_GAS;

    u.gasSpent += delta;
    totalGasSpent += delta;
    totalCalls += 1;
    if (rebatePerGas > 0) {
        uint256 reward = delta * rebatePerGas;
        u.claimable += reward;
        totalOwed += reward;
    }
    emit Activity(msg.sender, delta, u.gasSpent, block.timestamp, context);
}

/// @notice Owner-adjustable cap on slots per heavy call (gas safety).
function setMaxHeavySlots(uint256 _max) external onlyOwner {
    maxHeavySlots = _max;
}

function heavyRecordCount(address user) external view returns (uint256) {
    return heavyRecords[user].length;
}
}
